version: '2'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000  --workers 4 --keep-alive 300 --timeout 300 cando.wsgi:application
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
    - ./:/srv

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
    - django
    volumes:
    - ./conf:/etc/nginx/conf.d
    - app-files:/srv/cando
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file: .env
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
  
volumes:
  app-files:
    driver: local
    driver_opts:
      type: nfs
      device: ./
      o: bind
