# Generated by Django 3.1.6 on 2021-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(default='', max_length=140)),
                ('body', models.TextField(max_length=20000)),
                ('image', models.ImageField(upload_to='static/blog_images')),
            ],
        ),
    ]
